name: Sync Public Branch to Public Repo

on:
  push:
    branches:
      - public 

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Public Branch
        uses: actions/checkout@v3
        with:
          ref: public

      - name: Set up Git config
        run: |
          git config --global user.name "Your Bot Name"
          git config --global user.email "yourusername@users.noreply.github.com"

      - name: Remove default origin remote
        run: git remote remove origin

      - name: Add Public Repo as Remote
        run: |
          git remote add publicRepo "https://benjonesdata:${{ secrets.PAT_TOKEN }}@github.com/benjonesdata/bayes-ball-public.git"

      - name: List remotes for debugging
        run: git remote -v

      - name: Push changes to Public Repo
        run: |
          git push publicRepo public:main --force
